"""baseline: 9 tabellen multi-user fundament

Revision ID: 87f352f6ec00
Revises: 
Create Date: 2026-06-16 19:53:17.079514
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87f352f6ec00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('iata', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('is_origin_seed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('iata')
    )
    op.create_index('ix_airports_country', 'airports', ['country_code'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('nights', sa.SmallInteger(), nullable=False),
    sa.Column('out_date', sa.Date(), nullable=False),
    sa.Column('in_date', sa.Date(), nullable=False),
    sa.Column('out_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('in_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'EUR'"), nullable=False),
    sa.Column('found_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'origin', 'destination', 'nights', 'out_date', 'in_date', name='uq_deals_combo')
    )
    op.create_index('ix_deals_match', 'deals', ['origin', 'nights', 'total_price'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('tier', sa.String(length=16), server_default=sa.text("'free'"), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("status IN ('active','paused','deleted')", name='ck_users_status'),
    sa.CheckConstraint("tier IN ('free','premium')", name='ck_users_tier'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('auth_tokens',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('email_login','telegram_link')", name='ck_auth_tokens_purpose'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_auth_tokens_expires', 'auth_tokens', ['expires_at'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('opted_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('telegram','email','whatsapp')", name='ck_channels_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'address', name='uq_channels_type_address')
    )
    op.create_index('ix_channels_user', 'channels', ['user_id'], unique=False)
    op.create_table('preferences',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('months_ahead', sa.SmallInteger(), server_default=sa.text('3'), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'EUR'"), nullable=False),
    sa.Column('alert_mode', sa.String(length=16), server_default=sa.text("'instant'"), nullable=False),
    sa.Column('dest_filter_mode', sa.String(length=16), server_default=sa.text("'all'"), nullable=False),
    sa.Column('trip_lengths', postgresql.ARRAY(sa.SmallInteger()), server_default=sa.text("'{3,5,7}'"), nullable=False),
    sa.Column('dest_countries', postgresql.ARRAY(sa.String(length=2)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('dest_whitelist', postgresql.ARRAY(sa.String(length=3)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('dest_blacklist', postgresql.ARRAY(sa.String(length=3)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("alert_mode IN ('instant','digest')", name='ck_preferences_alert_mode'),
    sa.CheckConstraint("dest_filter_mode IN ('all','country','whitelist','blacklist')", name='ck_preferences_dest_mode'),
    sa.CheckConstraint('months_ahead BETWEEN 1 AND 12', name='ck_preferences_months'),
    sa.CheckConstraint('threshold > 0', name='ck_preferences_threshold_pos'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sent_alerts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('nights', sa.SmallInteger(), nullable=False),
    sa.Column('channel_type', sa.String(length=16), nullable=False),
    sa.Column('alerted_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('out_date', sa.Date(), nullable=False),
    sa.Column('in_date', sa.Date(), nullable=False),
    sa.Column('last_alerted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'origin', 'destination', 'nights', 'channel_type', name='uq_sent_alerts_fingerprint')
    )
    op.create_index('ix_sent_alerts_user', 'sent_alerts', ['user_id'], unique=False)
    op.create_table('user_origins',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('origin_iata', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['origin_iata'], ['airports.iata'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'provider_id', 'origin_iata')
    )
    op.create_index('ix_user_origins_provider_origin', 'user_origins', ['provider_id', 'origin_iata'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_origins_provider_origin', table_name='user_origins')
    op.drop_table('user_origins')
    op.drop_index('ix_sent_alerts_user', table_name='sent_alerts')
    op.drop_table('sent_alerts')
    op.drop_table('preferences')
    op.drop_index('ix_channels_user', table_name='channels')
    op.drop_table('channels')
    op.drop_index('ix_auth_tokens_expires', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index('uq_users_email_lower', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_table('users')
    op.drop_table('providers')
    op.drop_index('ix_deals_match', table_name='deals')
    op.drop_table('deals')
    op.drop_index('ix_airports_country', table_name='airports')
    op.drop_table('airports')
    # ### end Alembic commands ###
